
USE [ALL_DEPARTEMENT]

IF OBJECT_ID('dbo.Departement', 'U') IS NOT NULL 
DROP TABLE dbo.Departement
GO 
IF OBJECT_ID('dbo.Employe', 'U') IS NOT NULL 
DROP TABLE dbo.Employe
GO 

CREATE TABLE Departement (
	DNO INT PRIMARY KEY IDENTITY(1,1)  NOT NULL ,
	DNOM VARCHAR(50), 
	DIR VARCHAR(50),
	VILLE VARCHAR(50)
)
GO 

CREATE TABLE Employe(
	ENO INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
	ENOM VARCHAR(50), 
	PROF VARCHAR(50) , 
	DATEEMB Date, 
	SAL VARCHAR(80), 
	COMM VARCHAR(80), 
	DNO INT NOT NULL,
	FOREIGN KEY (DNO) REFERENCES Departement(DNO)
		ON UPDATE CASCADE 
		ON DELETE CASCADE
)