insert into Departement (DNOM, DIR, VILLE) values ('Human Resources', 'Melisenda Dupre', 'Kisarazu');
insert into Departement (DNOM, DIR, VILLE) values ('Sales', 'Abramo Fenton', 'Grodzisk Mazowiecki');
insert into Departement (DNOM, DIR, VILLE) values ('Human Resources', 'Deeyn Berryman', 'Santulhão');
insert into Departement (DNOM, DIR, VILLE) values ('Legal', 'Berke Lamberti', 'Brusyliv');
insert into Departement (DNOM, DIR, VILLE) values ('Training', 'Tresa Shama', 'Youdian');
insert into Departement (DNOM, DIR, VILLE) values ('Research and Development', 'Morissa Boundy', 'Mantes-la-Jolie');
insert into Departement (DNOM, DIR, VILLE) values ('Accounting', 'Pinchas Malec', 'Devnya');
insert into Departement (DNOM, DIR, VILLE) values ('Services', 'Evyn Sinnat', 'Kilimatinde');
insert into Departement (DNOM, DIR, VILLE) values ('Services', 'Palmer Kelby', 'Delgermörön');
insert into Departement (DNOM, DIR, VILLE) values ('Engineering', 'Melania Berg', 'Zubrzyca Dolna');
insert into Departement (DNOM, DIR, VILLE) values ('Business Development', 'Sarine Larman', 'Longquan');
insert into Departement (DNOM, DIR, VILLE) values ('Human Resources', 'Harv Prahl', 'Rusocice');
insert into Departement (DNOM, DIR, VILLE) values ('Accounting', 'Emeline Ferrers', 'Tarlac City');
insert into Departement (DNOM, DIR, VILLE) values ('Product Management', 'Oberon Hubbins', 'Auch');
insert into Departement (DNOM, DIR, VILLE) values ('Training', 'Milka Hansmann', 'Ica');
insert into Departement (DNOM, DIR, VILLE) values ('Services', 'Spence Gratrix', 'Dami');
insert into Departement (DNOM, DIR, VILLE) values ('Training', 'Hermy Bartels-Ellis', 'Sanqishi');
insert into Departement (DNOM, DIR, VILLE) values ('Marketing', 'Barbra Reinbech', 'Villa de Soto');
insert into Departement (DNOM, DIR, VILLE) values ('Support', 'Bidget Hutchings', 'Sápes');
insert into Departement (DNOM, DIR, VILLE) values ('Sales', 'Colan Slemming', 'Cibunut');
insert into Departement (DNOM, DIR, VILLE) values ('Sales', 'Burlie Whiskin', 'Austin');
insert into Departement (DNOM, DIR, VILLE) values ('Services', 'Dorita Baron', 'Wādī al ‘Uyūn');
insert into Departement (DNOM, DIR, VILLE) values ('Support', 'Vern Comiam', 'Datong');
insert into Departement (DNOM, DIR, VILLE) values ('Legal', 'Courtney Soldi', 'Yangchengzhuang');
insert into Departement (DNOM, DIR, VILLE) values ('Services', 'Jaime Mirando', 'Pereira');
insert into Departement (DNOM, DIR, VILLE) values ('Support', 'Dillie Mincini', 'Concepción');
insert into Departement (DNOM, DIR, VILLE) values ('Human Resources', 'Chandal Kuhwald', 'Néos Oropós');
insert into Departement (DNOM, DIR, VILLE) values ('Legal', 'Wadsworth Vlasyev', 'Daiyue');
insert into Departement (DNOM, DIR, VILLE) values ('Marketing', 'Shani Crady', 'Talalayivka');
insert into Departement (DNOM, DIR, VILLE) values ('Research and Development', 'Robby Pieter', 'Sombor');
insert into Departement (DNOM, DIR, VILLE) values ('Legal', 'Zacharia Vergine', 'Longhua');
insert into Departement (DNOM, DIR, VILLE) values ('Business Development', 'Lolita Gotobed', 'Chenôve');
insert into Departement (DNOM, DIR, VILLE) values ('Product Management', 'Marianna Saddler', 'Mandi Bahāuddīn');
insert into Departement (DNOM, DIR, VILLE) values ('Accounting', 'Sayres Adshead', 'Taxisco');
insert into Departement (DNOM, DIR, VILLE) values ('Accounting', 'Hewe Arnald', 'Krathum Baen');
insert into Departement (DNOM, DIR, VILLE) values ('Legal', 'Daryn Schoenrock', 'Terter');
insert into Departement (DNOM, DIR, VILLE) values ('Support', 'Terrel Sutherland', 'Greeley');
insert into Departement (DNOM, DIR, VILLE) values ('Training', 'Tersina Thurlborn', 'Louisville');
insert into Departement (DNOM, DIR, VILLE) values ('Legal', 'Fredi Zupo', 'Okuta');
insert into Departement (DNOM, DIR, VILLE) values ('Training', 'Shelia Standell', 'Zhiletovo');
insert into Departement (DNOM, DIR, VILLE) values ('Legal', 'Jacquelyn Hornung', 'Hefei');
insert into Departement (DNOM, DIR, VILLE) values ('Product Management', 'Hermione Mullane', 'Villa Altagracia');
insert into Departement (DNOM, DIR, VILLE) values ('Marketing', 'Deedee Pirrone', 'Gongjiang');
insert into Departement (DNOM, DIR, VILLE) values ('Human Resources', 'Trish Karp', 'Gaotian');
insert into Departement (DNOM, DIR, VILLE) values ('Human Resources', 'Hulda Gottschalk', 'Shuiyang');
insert into Departement (DNOM, DIR, VILLE) values ('Marketing', 'Sherri Cowlam', 'Carvalhinho');
insert into Departement (DNOM, DIR, VILLE) values ('Engineering', 'Mic Walburn', 'Balingcanaway');
insert into Departement (DNOM, DIR, VILLE) values ('Marketing', 'Anabel Jiggens', 'Terawas');
insert into Departement (DNOM, DIR, VILLE) values ('Marketing', 'Sig Vlasin', 'Huangben');
insert into Departement (DNOM, DIR, VILLE) values ('Engineering', 'Darin Guerrero', 'Smedjebacken');
insert into Departement (DNOM, DIR, VILLE) values ('Research and Development', 'Nikolaus Wilkennson', 'Timeng');
insert into Departement (DNOM, DIR, VILLE) values ('Training', 'Irena Dollman', 'Itajubá');
insert into Departement (DNOM, DIR, VILLE) values ('Research and Development', 'Phillis Lambdin', 'Mont-Royal');
insert into Departement (DNOM, DIR, VILLE) values ('Research and Development', 'Shannon Tenbrug', 'Kebonan');
insert into Departement (DNOM, DIR, VILLE) values ('Business Development', 'Wilie Boxe', 'Luts’k');
insert into Departement (DNOM, DIR, VILLE) values ('Human Resources', 'Anna-diana Boon', 'Jelbuk');
insert into Departement (DNOM, DIR, VILLE) values ('Support', 'Minerva Petticrow', 'Tinambac');
insert into Departement (DNOM, DIR, VILLE) values ('Marketing', 'Elena Garman', 'Tekik Wetan');
insert into Departement (DNOM, DIR, VILLE) values ('Human Resources', 'Pieter Biddell', 'Al Mayādīn');
insert into Departement (DNOM, DIR, VILLE) values ('Sales', 'Kira Rowles', 'Karangdawa Barat');
insert into Departement (DNOM, DIR, VILLE) values ('Legal', 'Peder Mongeot', 'Golubac');
insert into Departement (DNOM, DIR, VILLE) values ('Human Resources', 'Calida Muehle', 'Pécs');
insert into Departement (DNOM, DIR, VILLE) values ('Accounting', 'Maureene Crank', 'Himeji');
insert into Departement (DNOM, DIR, VILLE) values ('Sales', 'Nicoline McKerlie', 'Yong’an');
insert into Departement (DNOM, DIR, VILLE) values ('Marketing', 'Courtenay Spritt', 'Phitsanulok');
insert into Departement (DNOM, DIR, VILLE) values ('Training', 'Julius Rawdall', 'Al Funayţīs');
insert into Departement (DNOM, DIR, VILLE) values ('Marketing', 'Hanni Lyes', 'Plakhtiyivka');
insert into Departement (DNOM, DIR, VILLE) values ('Legal', 'Nikolaos Kunzler', 'Novoshakhtinskiy');
insert into Departement (DNOM, DIR, VILLE) values ('Marketing', 'Agneta Parris', 'Cullhuas');
insert into Departement (DNOM, DIR, VILLE) values ('Services', 'Jared Valentine', 'Woja');
insert into Departement (DNOM, DIR, VILLE) values ('Human Resources', 'Billy Moon', 'Thành Phố Uông Bí');
insert into Departement (DNOM, DIR, VILLE) values ('Sales', 'Morley Frichley', 'Muheza');
insert into Departement (DNOM, DIR, VILLE) values ('Support', 'Gae Bavridge', 'Xicun');
insert into Departement (DNOM, DIR, VILLE) values ('Sales', 'Rickie Simoneton', 'Torrevieja');
insert into Departement (DNOM, DIR, VILLE) values ('Support', 'Aurora Killingworth', 'Lhakangtang');
insert into Departement (DNOM, DIR, VILLE) values ('Product Management', 'Dell McClements', 'Vallentuna');
insert into Departement (DNOM, DIR, VILLE) values ('Legal', 'Johnna Blackler', 'Shimen');
insert into Departement (DNOM, DIR, VILLE) values ('Training', 'Carol-jean Climson', 'Não Me Toque');
insert into Departement (DNOM, DIR, VILLE) values ('Research and Development', 'Paddie Chasemoore', 'Spas-Klepiki');
insert into Departement (DNOM, DIR, VILLE) values ('Legal', 'Myrta Hourstan', 'Esperanza');
insert into Departement (DNOM, DIR, VILLE) values ('Marketing', 'Archibaldo Buske', 'Tekeli');
insert into Departement (DNOM, DIR, VILLE) values ('Marketing', 'Quintina Meharry', 'Lijia');
insert into Departement (DNOM, DIR, VILLE) values ('Engineering', 'Wolfgang Gristock', 'Izobil’nyy');
insert into Departement (DNOM, DIR, VILLE) values ('Business Development', 'Buddie Chelam', 'La Mesa');
insert into Departement (DNOM, DIR, VILLE) values ('Human Resources', 'Miranda Imrie', 'Kanie');
insert into Departement (DNOM, DIR, VILLE) values ('Product Management', 'Culley Dabs', 'Yamaguchi-shi');
insert into Departement (DNOM, DIR, VILLE) values ('Product Management', 'Francene Blazy', 'Livingstone');
insert into Departement (DNOM, DIR, VILLE) values ('Product Management', 'Kacey Juzek', 'Klimovsk');
insert into Departement (DNOM, DIR, VILLE) values ('Research and Development', 'Pascal Kimbly', 'Ljungby');
insert into Departement (DNOM, DIR, VILLE) values ('Human Resources', 'Felicia Giotto', 'Chirpan');
insert into Departement (DNOM, DIR, VILLE) values ('Engineering', 'Belia Nevison', 'Halong');
insert into Departement (DNOM, DIR, VILLE) values ('Research and Development', 'Corenda Shellibeer', 'Lukou');
insert into Departement (DNOM, DIR, VILLE) values ('Engineering', 'Sharleen Frederick', 'Tegalagung');
insert into Departement (DNOM, DIR, VILLE) values ('Support', 'Herrick Phillot', 'Maimará');
insert into Departement (DNOM, DIR, VILLE) values ('Support', 'Madeline Waylett', 'Muramvya');
insert into Departement (DNOM, DIR, VILLE) values ('Support', 'Any Best', 'Mantang');
insert into Departement (DNOM, DIR, VILLE) values ('Training', 'Natala Staves', 'Kalisari');
insert into Departement (DNOM, DIR, VILLE) values ('Support', 'Nolana Touzey', 'Srebrenica');
insert into Departement (DNOM, DIR, VILLE) values ('Research and Development', 'Benjie Probet', 'Nacka');
insert into Departement (DNOM, DIR, VILLE) values ('Sales', 'Kiele Penk', 'Kutamangu');